### ISSUE TITLE
IMU scale factor

### ISSUE THREAD

**Issue by dpkoch** [byu-magicc/fcu_io#2]
Hey @superjax, so I see the manual scale factors you added for IMU. I'm thinking we should instead apply the scale factors we calculated on the naze before sending them over MAVlink, so that they're in normal units (um/s^2 and urad/s or whatever we decided on) before they go over the wire. Thoughts?

**Comment by superjax** [comment]
The only difference is that we have to crank up the IMU stuff to int32_t instead of int16_t.  Representing in different units is not as accurate in int16, so we need the extra bits to keep the same information.  In the interest of speed, I think it would be better to keep them int16s, rather than doubling the message size for convenience.

**Comment by superjax** [comment]
We could set a Mavlink Param with the scale factor, which could be requested from the board.  That doesn't really make perfect sense, because you wouldn't ever change it from the ground station, but it at least would be accessible from the ground station and the board.
