### ISSUE TITLE
boost thread: trying joining itself: Resource deadlock avoided..

### ISSUE THREAD

**Issue by DengueTim** [byu-magicc/fcu_io#42]
Hi. 
   I worked through the install instructions but got this error when starting the node with rosrun:

`tp@nugget:~/byu/catkin_ws$ rosrun fcu_io fcu_io_node 
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::thread_resource_error> >'
  what():  boost thread: trying joining itself: Resource deadlock avoided
Aborted (core dumped)
tp@nugget:~/byu/catkin_ws$`

This is with ROS Kinetic on Ubuntu 16.04 which I know isn't supported yet.  I thought I'd ask anyway.

I was looking at using Cleanflight with MSP till I found this.  It seems a much better approach. Thanks for sharing your work on a great project!

Tim.

**Comment by superjax** [comment]
You're welcome!

Just so you know, I would label this project as in 'beta' state.  It's pretty stable, but it's not perfect yet, and we will likely make quite a few improvements, specifically to the ROSflight code, but fcu_io works really well.

The error that you are seeing is the same error that happens when you unplug the board while the node is running.  I would check to make sure that you are using the right port.  We don't have automatic port detection working yet, so you may want to make sure that fcu_io is connecting to the right device.  The easiest way to check the port is to unplug the board, and `ls /dev`.  That will list a bunch of devices on your comptuer.  Re-plug the board and `ls /dev` again.  Look for the difference.  It will likely be in `/dev/ttyUSBX` or something like that, but in your case, it's probably not `USB0`.

`fcu_io` uses a parameter to decide which port it looks for the naze on, and you can specify it on launch with `rosrun fcu_io fcu_io_node _port:=/dev/ttyUSBX`

**Comment by dpkoch** [comment]
@DengueTim, I'm glad you're interested in the project! Hopefully it's helpful to you.

@superjax I tried testing your theory out by running `fcu_io` with the `_port` parameter set to the wrong device. When I do this, I get the following error instead of the one @DengueTim is seeing:

```
[FATAL] [1473785935.926571626]: Serial Error: open: No such file or directory
Segmentation fault
```

It'd be nice to get rid of the seg fault, but regardless this seems like a different error. The error @DengueTim is seeing is the one that I get when I unplug the Naze after `fcu_io` is already running. I'm not sure why that error is showing up on startup; possibly it's a problem with 16.04/Kinetic specifically that doesn't affect 14.04/Indigo. I'll see if I can reproduce the problem on 16.04/Kinetic and look into it from there

**Comment by DengueTim** [comment]
Thanks for your comments guys.   The error is returned almost instantly.  Unpluging the Flip32 rosrun actually takes longer to return the `Serial Error..` error.

Running `make listen` in the ROSflight project returns:
`tp@nugget:~/byu/ROSflight$ make listen
miniterm.py /dev/ttyUSB0 115200
--- Miniterm on /dev/ttyUSB0  115200,8,N,1 ---
`
and then a whole load of random data with q's and ('s.  It looks like the Flip32/naze is on /dev/ttyUSB0 okay.

Maybe it's related to the version of libboost or gcc that ships with ubuntu 16.04...  Unfortunately my C++ isn't good enough to track this down yet.  I would like to help if I could.

**Comment by superjax** [comment]
@DengueTim - You're just getting the MAVlink packets scrambled up converted directly to ascii at the wrong baudrate.  But it you're right, it does seem to be transmitting, and it looks like you're on the right port.

@dpkoch - you're totally right, sorry about my earlier suggestion.  Unfortunately, I don't have a 16.04 machine handy with me. Laith's old laptop has 16.04 running on it.  It's in the bookshelf by David's desk.  If I were there I would use that to track down the issue.  Just in case you were looking for an easy 16.04 machine.

**Comment by dpkoch** [comment]
Quick update: I tested fcu_io on 16.04/Kinetic, and didn't have any problems. Without being able to duplicate the bug it's going to be pretty difficult to track down. @DengueTim are there any other details about your setup you think might be relevant? Are you using an x86 computer or an ARM computer?

**Comment by DengueTim** [comment]
@dpkoch Thanks for trying it out on 16.04/Kinetic.  Following your comment I tried apt-get update & upgrade.  It updated a load of ROS packages.  After that and rebuilding fcu_common and fcu_io2 it now seems to be working.   Sorry. I should have insured things were up to date before opening the issue.  Hopefully this will help anyone else who has the same error.

I'm using a second gen i7 laptop.  I'll try it on an ARM Cortex-a17 device soon.

**Comment by DengueTim** [comment]
Turns out this has nothing to do with the apt-get update.  It seems if you run 'make listen' it does something to the state of the cp210x or usbserial kernel module.  Removing the modules with rmmod and reconnecting the device restores things to a working state.

**Comment by mmmfarrell** [comment]
I just had the same issue using an Odroid XU4 with Ubuntu 16.04. For me, the fix was setting the "baud" parameter for the fcu_io_node to 921600
